/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package callcenter;

/**
 *
 * @author Usuario
 */
public class interfaz extends javax.swing.JFrame {

    static interfaz ventana = new interfaz();
    
    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        Datos arranque = new Datos();
        
        SimLlamador llamador = new SimLlamador();
        Thread hiloLlamador = new Thread(llamador);
        hiloLlamador.start();
        
    }

    public static void actualizar(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOperario1 = new javax.swing.JLabel();
        txtOperario2 = new javax.swing.JLabel();
        txtOperario3 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JLabel();
        txtUsuario2 = new javax.swing.JLabel();
        txtUsuario3 = new javax.swing.JLabel();
        btncolg1 = new javax.swing.JButton();
        btncolg2 = new javax.swing.JButton();
        btncolg3 = new javax.swing.JButton();
        txtencola = new javax.swing.JLabel();
        txtnumcol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtOperario1.setText("jLabel1");

        txtOperario2.setText("jLabel2");

        txtOperario3.setText("jLabel3");

        txtUsuario1.setText("jLabel4");

        txtUsuario2.setText("jLabel5");

        txtUsuario3.setText("jLabel6");

        btncolg1.setText("Colgar");
        btncolg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolg1ActionPerformed(evt);
            }
        });

        btncolg2.setText("Colgar");
        btncolg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolg2ActionPerformed(evt);
            }
        });

        btncolg3.setText("Colgar");
        btncolg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolg3ActionPerformed(evt);
            }
        });

        txtencola.setText("En cola:");

        txtnumcol.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOperario1)
                    .addComponent(txtOperario2)
                    .addComponent(txtOperario3))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUsuario3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btncolg3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtUsuario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncolg2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncolg1)))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(txtencola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnumcol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperario1)
                    .addComponent(txtUsuario1)
                    .addComponent(btncolg1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperario2)
                    .addComponent(txtUsuario2)
                    .addComponent(btncolg2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperario3)
                    .addComponent(txtUsuario3)
                    .addComponent(btncolg3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtencola)
                    .addComponent(txtnumcol))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncolg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolg1ActionPerformed
        Datos.colgarLlamada(Datos.getOperarios()[0]);
    }//GEN-LAST:event_btncolg1ActionPerformed

    private void btncolg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolg2ActionPerformed
        Datos.colgarLlamada(Datos.getOperarios()[1]);
    }//GEN-LAST:event_btncolg2ActionPerformed

    private void btncolg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolg3ActionPerformed
        Datos.colgarLlamada(Datos.getOperarios()[2]);
    }//GEN-LAST:event_btncolg3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ventana.setVisible(true);
    }
    
    public void refrescar(){
        Telefono tel1 = Datos.getOperarios()[0];
        Telefono tel2 = Datos.getOperarios()[1];
        Telefono tel3 = Datos.getOperarios()[2];
        
        this.txtOperario1.setText(tel1.getEmpleado());
        this.txtOperario2.setText(tel2.getEmpleado());
        this.txtOperario3.setText(tel3.getEmpleado());
        
        this.btncolg1.setVisible(!tel1.Disponible);
        this.btncolg2.setVisible(!tel2.Disponible);
        this.btncolg3.setVisible(!tel3.Disponible);
        
        if(tel1.Disponible){
            this.txtUsuario1.setText("Disponible");
        }else{
            this.txtUsuario1.setText(Datos.getLlamadasEnAtencion()[0].getUsuario().getNombre());
        }
        if(tel2.Disponible){
            this.txtUsuario2.setText("Disponible");
        }else{
            this.txtUsuario2.setText(Datos.getLlamadasEnAtencion()[1].getUsuario().getNombre());
        }
        if(tel3.Disponible){
            this.txtUsuario3.setText("Disponible");
        }else{
            this.txtUsuario3.setText(Datos.getLlamadasEnAtencion()[2].getUsuario().getNombre());
        }
        
        this.txtnumcol.setText(Datos.cantidadEnCola());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncolg1;
    private javax.swing.JButton btncolg2;
    private javax.swing.JButton btncolg3;
    private javax.swing.JLabel txtOperario1;
    private javax.swing.JLabel txtOperario2;
    private javax.swing.JLabel txtOperario3;
    private javax.swing.JLabel txtUsuario1;
    private javax.swing.JLabel txtUsuario2;
    private javax.swing.JLabel txtUsuario3;
    private javax.swing.JLabel txtencola;
    private javax.swing.JLabel txtnumcol;
    // End of variables declaration//GEN-END:variables
}
